fun:
	gcc -Wall -ansi -pedantic-errors fun.c -o fun -lm
	
funi:
	gcc -Wall -ansi -pedantic-errors funi.c -o funi -lm	

hello:
	gcc -Wall -ansi -pedantic-errors hello.c -o helloo -lm

clean:
	rm -f fun
	rm -f funi
	rm -f hello
