all:
	g++ -std=c++17 -O3 -Wall -Wextra -pedantic atomic.cpp -o atom -lpthread
	g++ -std=c++17 -O3 -Wall -Wextra -pedantic sema.cpp -o incs -lpthread
	g++ -std=c++17 -O3 -Wall -Wextra -pedantic spinlock.cpp -o incsi -lpthread
